# **청와대 청원 분류**

# 1. 문제 확인하기

test 데이터의 주제/범주를 구분하는 문제

* 0 : 인권/성평등
* 1 : 문화/예술/체육/언론
* 2 : 육아/교육

### -1. 데이터 불러오기

In [1]:
import io
from google.colab import files
myfile = files.upload()

Saving sample_submission.csv to sample_submission.csv
Saving test(8).csv to test(8).csv
Saving train(8).csv to train(8).csv

In [2]:
import pandas as pd

#로컬 파일에 존재하는 데이터를 변수에 저장하기
train = pd.read_csv(io.BytesIO(myfile['train(8).csv']))
test = pd.read_csv(io.BytesIO(myfile['test(8).csv']))
submission = pd.read_csv(io.BytesIO(myfile['sample_submission.csv']))

In [3]:
train.head(10)

   index  category                                               data
0      0         2  신혼부부위한 주택정책 보다 보육시설 늘려주세요.. 국민세금으로 일부를 위한 정책펴지...
1      1         0  학교이름에 '남자'도 붙여주세요. 울산여자중학교에 재학중인 학생입니다 최근 양성평등...
2      2         1  빙상연맹, 대한축구협회등 각종 체육협회의 비리를 철저하게 밝혀주세요.. 최근 동계올...
3      3         1  티비 12세,15세 관람가도 연령확인 의무화 하자.. 제기 에전에 티비를 보다가 잠...
4      4         1  무더운 여름철엔 남성들도 시원한 자율복장을 해야. 무더운 여름철에는 남성들도 노넥타...
5      5         1  일간베스트 사이트 폐쇠를 청원합니다. 국익에 전혀 도움이 되지  않고 국민에게 해를...
6      6         0  '초중고학교 페미니즘교육의무화'중복동의인원 무효처리해 주세요!!. 국민들의 요구를 ...
7      7         2  수시 발표도 다 7일 미뤄주세요.. 수능 전 발표를 피하기 위해 수능 후 발표나는 ...
8      8         0  여성부 폐지 청원합니다.. 여성이 인구 절반인데 여성 관련 정책은 보건복지부 기획재...
9      9         0  왜 제 수백만원짜리 녹취록을 증거로 인정해 주지 않습니까?. 한 사람을 잘 못 만난...

In [4]:
test.head()

   index                                               data
0      0  소년법 폐지해주세요. 법 아래에서 보호받아야 할 아이들이\n법으로 인해 보호받지 못...
1      1  국공립 유치원 증설에 관하여. 국공립 유치원 부지 학보와건립및 증설에\n*지역 어린...
2      2                   나경원파면. 나경원의원의  동계올림픽 위원을 파면해 주세요
3      3  국민위원에가 삼성편만들어요. 삼성에서 11년간  일하고 혈암과 백혈병 진단을 받은 ...
4      4  방과후,유치원,어린이집 영어교육을 유지시켜주세요. 저는 아이 셋 키우는 평범한 주부...

In [5]:
submission.head()

   index  category
0      0         0
1      1         0
2      2         0
3      3         0
4      4         0

# 2. 데이터 전처리

훈련용 데이터 정보 확인 후 결측치 처리

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index     40000 non-null  int64
 1   category  40000 non-null  int64
 2   data      39992 non-null  object
dtypes: int64(2), object(1)
memory usage: 937.6+ KB

In [7]:
train = train[train['data'].notnull()]

In [8]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 39992 entries, 0 to 39999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index     39992 non-null  int64
 1   category  39992 non-null  int64
 2   data      39992 non-null  object
dtypes: int64(2), object(1)
memory usage: 1.2+ MB

In [9]:
#주제/범주 클래스 구성 확인
train['category'].value_counts()

2    13358
1    13335
0    13299
Name: category, dtype: int64

In [10]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   5000 non-null   int64
 1   data    5000 non-null   object
dtypes: int64(1), object(1)
memory usage: 78.2+ KB

test데이터는 결측치가 존재하지 않으므로 작업할 것이 없음

In [11]:
from tqdm import tqdm
import re
train_text = list(train['data'])

clear_text_list = []

for i in tqdm(range(len(train_text))):
    plain_text = str(train_text[i])

    clear_text = plain_text.replace("\\","").replace("n"," ")

    clear_text = re.sub('[-=+,#/\?:^$.@*\"※~&%ㆍ!』\\‘|\(\)\[\]\<\>`\'…》]', '', clear_text)
    
    clear_text_list.append(clear_text)

train['clear_text'] = clear_text_list
train

100%|██████████| 39992/39992 [00:00<00:00, 67270.08it/s]

,index,category,data,clear_text
0,0,2,신혼부부위한 주택정책 보다 보육시설 늘려주세요.. 국민세금으로 일부를 위한 정책펴지...,신혼부부위한 주택정책 보다 보육시설 늘려주세요 국민세금으로 일부를 위한 정책펴지 마...
1,1,0,학교이름에 '남자'도 붙여주세요. 울산여자중학교에 재학중인 학생입니다 최근 양성평등...,학교이름에 남자도 붙여주세요 울산여자중학교에 재학중인 학생입니다 최근 양성평등 글짓...
2,2,1,"빙상연맹, 대한축구협회등 각종 체육협회의 비리를 철저하게 밝혀주세요.. 최근 동계올...",빙상연맹 대한축구협회등 각종 체육협회의 비리를 철저하게 밝혀주세요 최근 동계올림픽에...
3,3,1,"티비 12세,15세 관람가도 연령확인 의무화 하자.. 제기 에전에 티비를 보다가 잠...",티비 12세15세 관람가도 연령확인 의무화 하자 제기 에전에 티비를 보다가 잠시 딴...
4,4,1,무더운 여름철엔 남성들도 시원한 자율복장을 해야. 무더운 여름철에는 남성들도 노넥타...,무더운 여름철엔 남성들도 시원한 자율복장을 해야 무더운 여름철에는 남성들도 노넥타이...
...,...,...,...,...
39995,39995,2,시간유연근무제. 저는 국립대에서 일하고 있는 비정규직 근로자입니다.\n동시에 두 ...,시간유연근무제 저는 국립대에서 일하고 있는 비정규직 근로자입니다 동시에 두 자녀의...
39996,39996,0,소년법을 폐지해 주시고 부산 여중생 가해자 학생들의 강력한 처벌을 요구합니다. 소년...,소년법을 폐지해 주시고 부산 여중생 가해자 학생들의 강력한 처벌을 요구합니다 소년법...
39997,39997,2,무서운데 지켜야 할게 있어요 도와주세요. 안녕하세요 . 한부모엄마 입니다.\n양육비...,무서운데 지켜야 할게 있어요 도와주세요 안녕하세요 한부모엄마 입니다 양육비를 받고...
39998,39998,2,교복에 고정식 이름표를 달게 하는 것을 금지해 주세요.. 교복에 이름표를 박아놓아...,교복에 고정식 이름표를 달게 하는 것을 금지해 주세요 교복에 이름표를 박아놓아 탈...
39999,39999,0,합의성관계 가능 나이연령을 올리십시오. 제가 형법공부를하다가 문제를풀고있는데\n금지...,합의성관계 가능 나이연령을 올리십시오 제가 형법공부를하다가 문제를풀고있는데 금지착오...

In [12]:
test_text = list(test['data'])

clear_text_list = []

for i in tqdm(range(len(test_text))):
    plain_text = str(test_text[i])

    clear_text = plain_text.replace("\\","").replace("n"," ")

    clear_text = re.sub('[-=+,#/\?:^$.@*\"※~&%ㆍ!』\\‘|\(\)\[\]\<\>`\'…》]', '', clear_text)
    
    clear_text_list.append(clear_text)

test['clear_text'] = clear_text_list
test

100%|██████████| 5000/5000 [00:00<00:00, 65813.44it/s]

,index,data,clear_text
0,0,소년법 폐지해주세요. 법 아래에서 보호받아야 할 아이들이\n법으로 인해 보호받지 못...,소년법 폐지해주세요 법 아래에서 보호받아야 할 아이들이 법으로 인해 보호받지 못하고...
1,1,국공립 유치원 증설에 관하여. 국공립 유치원 부지 학보와건립및 증설에\n*지역 어린...,국공립 유치원 증설에 관하여 국공립 유치원 부지 학보와건립및 증설에 지역 어린이 놀...
2,2,나경원파면. 나경원의원의 동계올림픽 위원을 파면해 주세요,나경원파면 나경원의원의 동계올림픽 위원을 파면해 주세요
3,3,국민위원에가 삼성편만들어요. 삼성에서 11년간 일하고 혈암과 백혈병 진단을 받은 ...,국민위원에가 삼성편만들어요 삼성에서 11년간 일하고 혈암과 백혈병 진단을 받은 사...
4,4,"방과후,유치원,어린이집 영어교육을 유지시켜주세요. 저는 아이 셋 키우는 평범한 주부...",방과후유치원어린이집 영어교육을 유지시켜주세요 저는 아이 셋 키우는 평범한 주부입니다...
...,...,...,...
4995,4995,페이스북 개인신상정보 개털렸는데 이대로... 존경하신 문재인 대통령님 ~!!\n얼마...,페이스북 개인신상정보 개털렸는데 이대로 존경하신 문재인 대통령님 얼마전 미국본사로...
4996,4996,아시안 게임에 야구프로스포츠 선수참여금지 청원합니다.. 뭐 대놓고 병역브로커 하자는...,아시안 게임에 야구프로스포츠 선수참여금지 청원합니다 뭐 대놓고 병역브로커 하자는것인...
4997,4997,손흥민국가대표자격 영구박탈청원합니다. 광고찍을때랑 군면제걸렸을때 소속팀 토튼햄에서만...,손흥민국가대표자격 영구박탈청원합니다 광고찍을때랑 군면제걸렸을때 소속팀 토튼햄에서만 ...
4998,4998,한진 사모님 이명희를 구속시키는 방안을 찿아보세요. 일단 밝혀진 피해자가 11명입니...,한진 사모님 이명희를 구속시키는 방안을 찿아보세요 일단 밝혀진 피해자가 11명입니다...
4999,4999,기저귀 갈아주는 장소로 공공기관 활용했으면. 손자가 생후 7개월 된 초보할머니입니다...,기저귀 갈아주는 장소로 공공기관 활용했으면 손자가 생후 7개월 된 초보할머니입니다 ...

# 3. 모델

**-1. 분석 모델 구축**

In [13]:
!pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting konlpy
  Downloading konlpy-0.6.0-py2.py3-none-any.whl (19.4 MB)
     |████████████████████████████████| 19.4 MB 8.5 MB/s
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.7/dist-packages (from konlpy) (1.21.6)
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.7/dist-packages (from konlpy) (4.9.1)
Collecting JPype1>=0.7.0
  Downloading JPype1-1.4.1-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (465 kB)
     |████████████████████████████████| 465 kB 37.3 MB/s
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from JPype1>=0.7.0->konlpy) (21.3)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from JPype1>=0.7.0->konlpy) (4.1.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->JPype1>=0.7.0->konlpy) (3.0.9)
Installing collected packages: JPype1, konlpy
Successfully installed JPype1-1.4.1 konlpy-0.6.0

**-2. 토큰화**

In [14]:
from konlpy.tag import Okt
from tqdm import tqdm

In [15]:
okt = Okt()

In [16]:
X_train = []

train_clear_text = list(train['clear_text'])

for i in tqdm(range(len(train_clear_text))):
    token_data = okt.morphs(train_clear_text[i]) #토큰화
    token_data = [word for word in token_data if len(word) > 1]
    X_train.append(token_data)
X_train[:1]

100%|██████████| 39992/39992 [25:38<00:00, 25.99it/s]

[['신혼부부',
  '주택',
  '정책',
  '보다',
  '보육',
  '시설',
  '늘려주세요',
  '국민',
  '세금',
  '으로',
  '일부',
  '정책',
  '펴지',
  '마시고',
  '보편',
  '으로',
  '모든',
  '국민',
  '수긍',
  '있는',
  '복지',
  '정책',
  '주시길',
  '바랍니다',
  '신혼부부',
  '이지만',
  '당첨',
  '되는',
  '사람',
  '로또',
  '되는',
  '이런',
  '주택',
  '정책',
  '반대',
  '합니다',
  '국민',
  '세금',
  '일부',
  '사람',
  '에게',
  '주기',
  '식이',
  '되면',
  '안되죠',
  '세금',
  '으로',
  '우리',
  '아이',
  '안전하게',
  '맡길',
  '있는',
  '보육',
  '시설',
  '전국',
  '설치',
  '주세요',
  '대기업',
  '솔선수범',
  '해서',
  '모든',
  '사업',
  '의무',
  '설치',
  '있도록',
  '하시구요',
  '보다',
  '맡길데가',
  '없어',
  '경력',
  '단절',
  '되는게',
  '괴롭습니다',
  '집은',
  '개인',
  '능력',
  '키워',
  '사는게',
  '맞습니다',
  '능력',
  '키울수',
  '있도록',
  '육아',
  '전담',
  '기울이는게',
  '맞습니다',
  '우리',
  '아이',
  '부모',
  '키우는거',
  '맞지만',
  '이제',
  '국가',
  '책임지는',
  '시대',
  '가는게',
  '맞다고',
  '봅니다',
  '그렇잖아도',
  '부동산',
  '가격',
  '자꾸',
  '올라가는게',
  '정부',
  '정책',
  '잘못',
  '되었다고',
  '봅니다',
  '부동산',
  '그냥',
  '내버려',
  '두세요',
  '건들',
  '수록',
  '역효과']]

In [17]:
X_test = []

test_clear_text = list(test['clear_text'])

for i in tqdm(range(len(test_clear_text))):
    token_data = okt.morphs(test_clear_text[i])
    token_data = [word for word in token_data if len(word) > 1]
    X_test.append(token_data)
X_test[:1]

100%|██████████| 5000/5000 [04:00<00:00, 20.81it/s]

[['소년법',
  '폐지',
  '해주세요',
  '아래',
  '에서',
  '보호',
  '받아야',
  '아이',
  '으로',
  '인해',
  '보호',
  '받지',
  '하고',
  '있습니다',
  '오히려',
  '악용',
  '하는',
  '사례',
  '늘어나고',
  '강도',
  '높아지고',
  '있습니다',
  '소년법',
  '폐지',
  '부탁드립니다']]

In [18]:
from keras.preprocessing.text import Tokenizer

max_words = 35000
tokenizer = Tokenizer(num_words = max_words)
tokenizer.fit_on_texts(X_train) 
X_train_vec = tokenizer.texts_to_sequences(X_train) 
X_test_vec = tokenizer.texts_to_sequences(X_test)

**-3. 모델 훈련**

In [19]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_len = 300
X_train_pad = pad_sequences(X_train_vec, maxlen = max_len)
X_test_pad = pad_sequences(X_test_vec, maxlen = max_len)

In [20]:
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(train['category'])

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Embedding

In [22]:
model = Sequential()
model.add(Embedding(max_words, 120))
model.add(LSTM(120))
model.add(Dense(3, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])

history = model.fit(X_train_pad, y_train, batch_size=128, epochs=15)

Epoch 1/15
313/313 [==============================] - 304s 963ms/step - loss: 0.5490 - acc: 0.7835
Epoch 2/15
313/313 [==============================] - 302s 965ms/step - loss: 0.2827 - acc: 0.9022
Epoch 3/15
313/313 [==============================] - 301s 960ms/step - loss: 0.2090 - acc: 0.9293
Epoch 4/15
313/313 [==============================] - 301s 962ms/step - loss: 0.1425 - acc: 0.9513
Epoch 5/15
313/313 [==============================] - 300s 959ms/step - loss: 0.1060 - acc: 0.9635
Epoch 6/15
313/313 [==============================] - 300s 958ms/step - loss: 0.0984 - acc: 0.9665
Epoch 7/15
313/313 [==============================] - 298s 953ms/step - loss: 0.1248 - acc: 0.9572
Epoch 8/15
313/313 [==============================] - 296s 945ms/step - loss: 0.1043 - acc: 0.9643
Epoch 9/15
313/313 [==============================] - 296s 944ms/step - loss: 0.0694 - acc: 0.9751
Epoch 10/15
313/313 [==============================] - 297s 947ms/step - loss: 0.0528 - acc: 0.9810
Epoch 11/15
313/313 [==============================] - 305s 973ms/step - loss: 0.0439 - acc: 0.9845
Epoch 12/15
313/313 [==============================] - 297s 950ms/step - loss: 0.0417 - acc: 0.9847
Epoch 13/15
313/313 [==============================] - 295s 944ms/step - loss: 0.0759 - acc: 0.9763
Epoch 14/15
313/313 [==============================] - 298s 952ms/step - loss: 0.1053 - acc: 0.9647
Epoch 15/15
313/313 [==============================] - 295s 942ms/step - loss: 0.0400 - acc: 0.9856

**-4. 예측 및 결과 저장**

In [23]:
y_pred = model.predict(X_test_pad)

157/157 [==============================] - 20s 125ms/step

In [31]:
import numpy as np
submission['category'] = np.argmax(y_pred, axis = -1)
submission.to_csv('submission_20003327_고민주.csv', index=False)

In [32]:
submission.head()

   index  category
0      0         2
1      1         2
2      2         1
3      3         1
4      4         2